# Generated by Django 3.2.14 on 2022-09-06 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('person_num', models.IntegerField()),
                ('book_date', models.DateField(blank=True)),
                ('book_time', models.PositiveSmallIntegerField(choices=[(1, '6:00PM'), (2, '7:00PM'), (3, '8:00PM'), (4, '9:00PM')])),
                ('is_booked', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('request_datetime', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('desk_id', models.AutoField(primary_key=True, serialize=False)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tablestatu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeofstatu', models.DateField(blank=True)),
                ('statuoftime', models.DateField(blank=True)),
                ('week_day', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday '), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('day_time', models.PositiveSmallIntegerField(choices=[(1, '6:00PM'), (2, '7:00PM'), (3, '8:00PM'), (4, '9:00PM')])),
                ('is_available', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('Desk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booktables.desk')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_confirm_time', models.DateTimeField(blank=True)),
                ('is_OK', models.BooleanField(default=False)),
                ('client_booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booktables.client_booking')),
                ('tablestatu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booktables.tablestatu')),
            ],
        ),
    ]
