# Generated by Django 3.2.14 on 2022-09-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client_booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='booktables.client_booking'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tablestatu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='booktables.tablestatu'),
        ),
    ]
