# Generated by Django 3.2.14 on 2022-09-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
