# Generated by Django 3.2.14 on 2022-09-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotions_name', models.CharField(max_length=200)),
                ('promotions_discount', models.IntegerField()),
                ('promotions_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('bestselling_item', models.CharField(max_length=200)),
                ('bestselling_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('bestselling_music', models.FileField(upload_to='music/%Y/%m/%d/')),
            ],
        ),
    ]
