# Generated by Django 3.2.14 on 2022-09-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0006_rename_type_name_item_type'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='bestselling_item',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='bestselling_photo',
        ),
        migrations.AddField(
            model_name='offer',
            name='Item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='menu_items.item'),
            preserve_default=False,
        ),
    ]
# example 'type_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu_items.type')