# Generated by Django 3.2.14 on 2022-09-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20220906_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
