# Generated by Django 3.2.14 on 2022-09-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu_items', '0006_rename_type_name_item_type'),
        ('offers', '0003_delete_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotions_name', models.CharField(max_length=200)),
                ('promotions_discount', models.IntegerField()),
                ('promotions_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('bestselling_music', models.FileField(upload_to='music/%Y/%m/%d/')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu_items.item')),
            ],
        ),
    ]
