# Generated by Django 3.2.14 on 2022-09-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Item',
            new_name='item',
        ),
    ]
