# Generated by Django 3.2.14 on 2022-09-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_rename_item_offer_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
