# Generated by Django 3.2.14 on 2022-09-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Silder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silder1', models.TextField(blank=True)),
                ('silder2', models.TextField(blank=True)),
                ('silder3', models.TextField(blank=True)),
            ],
        ),
    ]
