# Generated by Django 3.2.14 on 2022-09-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Silder',
        ),
    ]
