# Generated by Django 3.2.14 on 2022-09-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slider', '0002_delete_silder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider1', models.TextField(blank=True)),
                ('slider2', models.TextField(blank=True)),
                ('slider3', models.TextField(blank=True)),
            ],
        ),
    ]
