# Generated by Django 3.2.14 on 2022-09-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slider1',
            new_name='slider',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slider2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slider3',
        ),
    ]
