# Generated by Django 3.2.14 on 2022-08-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
    ]
