# Generated by Django 3.2.14 on 2022-08-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0003_alter_item_is_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lowcase_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
