# Generated by Django 3.2.14 on 2022-08-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0004_item_lowcase_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='lowcase_name',
        ),
    ]
