# Generated by Django 3.2.14 on 2022-08-24 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0005_remove_item_lowcase_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type_name',
            new_name='type',
        ),
    ]
